apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deployment # nome
spec:
  replicas: 1 # definindo 1 réplica
  selector: # rótulos
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: 762012032320.dkr.ecr.us-east-1.amazonaws.com/vaultwarden:latest # imagem da aplicação direto do ECR
          resources:
            limits: # limites de uso de cpu e memória
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts: # Volume persistent
            - name: vaultwarde-data 
              mountPath: /app/vaultwarden-data 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc